export const hostAddress = '10.177.19.12'
export const cas = 'https://'
export const auth = 'authenticationv2-uata.gdn-app.com/'
export const casLogout = cas + auth + 'cas/logout'
export const casLogin = cas + auth + 'cas/login?service=http://'
export const casCheck = ':8181/api/regen/cas-auth/check'